In [4]:
l1=range(10,20)

In [2]:
l1

range(10, 20)

In [3]:
print(l1)

range(10, 20)


In [4]:
list(l1)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [5]:
import numpy as np

In [6]:
a1=np.array(l1)

In [7]:
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
a1[4:9]

array([14, 15, 16, 17, 18])

In [9]:
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
a1[4]=56

In [14]:
a1

array([10, 11, 12, 13, 56, 15, 16, 17, 18, 19])

In [15]:
c=a1.copy()

In [16]:
c

array([10, 11, 12, 13, 56, 15, 16, 17, 18, 19])